name: compgeo
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.9
  - pip
  - ipywidgets
  - jupyterlab
  - jupytext
  - matplotlib
  - nodejs
  - numpy
  - pygmt
  - pyproj
  - scipy
  - tqdm
  - pip:
    - uncertainties
